/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 28mkbvcnJxn1WuXGx7J8H7

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantstYKdMn0FmPtu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tYKdMN0FmPTU/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantstYKdMn0FmPtu
});
